### ISSUE TITLE
Why is mine horrible lol

### ISSUE THREAD

**Issue by ThatOneCalculator** [Cynosphere/dumpy.js#1]
> Because this one is horrible in how it works.

Explain?

**Comment by ThatOneCalculator** [comment]
Actually, looking through the code, I can see why yours is better. Very good job! Just please note I didn't write the original algorithm, that was all pixer

**Comment by Cynosphere** [comment]
Reworked the description in the README to explain more in 5fc2235. Sorry for any unneeded hostility.

**Comment by ThatOneCalculator** [comment]
Hey! We don't actually rely on Imagemagick more, I'd love if you could remove that part, and maybe just say "sub optimal" instead of "horrible", I like your version but that does feel still really hostile

**Comment by Cynosphere** [comment]
It says "in the beginning"

**Comment by ThatOneCalculator** [comment]
I mean yea but still, a bit rude
